version: '3'

networks:
  cloudkit-net:
    driver: bridge
    name: cloudkit-net
services:
  cloudkit-img:
    image: ghcr.io/minimalcompact/thumbor
    container_name: cloudkit-img
    environment:
      # VIRTUAL_HOST is picked up by nginx-proxy. Here it's set for localhost
      # but you usually need to point it to your domain, e.g. thumbor.example.com
      - VIRTUAL_HOST=localhost
      # THUMBOR_NUM_PROCESSES control how many processes run inside the container
      # Normally this is set in connection with the number of CPU cores
      # Note however that you can also use the docker-compose scale option to dynamically
      # scale your thumbor instances
      - THUMBOR_NUM_PROCESSES=4
      # this would allow CORS from any origin (you can restrict to specific origins if you want)
      - CORS_ALLOW_ORIGIN=*
      # returns a webp image if browser Accept headers match
      - AUTO_WEBP=True
      # nginx-proxy does caching automatically, so no need to store the result storage cache
      # (this greatly speeds up and saves on CPU)
      - RESULT_STORAGE=thumbor.result_storages.no_storage
      - RESULT_STORAGE_STORES_UNSAFE=True
      - STORAGE=thumbor.storages.file_storage
      - UPLOAD_ENABLED=True
      - UPLOAD_PUT_ALLOWED=True
      - UPLOAD_DELETE_ALLOWED=True
      - THUMBOR_PORT=6501
    networks:
      - cloudkit-net
    ports:
     - "6501:6501"
   
  cloudkit-auth-cache:
    image: redis:6.2
    container_name: cloudkit-auth-cache
    networks:
      - cloudkit-net
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
  cloudkit-db:
    image: postgres:15
    container_name: cloudkit-db
    networks:
      - cloudkit-net
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=cloudkit-db
    ports:
      - 6500:5432
