export enum PATHS {
	ROOT = '/',
	API = '/api',
	PROFILE = '/profile',
	COLLECTIONS = '/collections',
	COLLECTION = '/collections/[id]'
}

export enum PATH_GROUPS {
	PUBLIC = '/(public)',
	PROTECTED = '/(protected)'
}
export enum SERVER_FORM_ACTIONS {
	LOGIN = 'login',
	REGISTER = 'register',
	SIGN_OUT = 'signOut',
	UPDATE_USER = 'updateUser',
	DELETE_USER = 'deleteUser',
	CREATE_COLLECTION = 'createCollection',
	EDIT_COLLECTION = 'editCollection',
	MOVE_COLLECTION = 'moveCollection',
	DELETE_COLLECTION = 'deleteCollection',
	ONBOARDING_COMPLETED = 'onboardingCompleted',
	ADD_ITEMS_TO_COLLECTION = 'addItemsToCollection',
	DELETE_ITEM_FROM_COLLECTION = 'deleteItemFromCollection',
	DELETE_MULTIPLE_ITEMS_FROM_COLLECTION = 'deleteMultipleItemsFromCollection',
	EDIT_ITEM_FROM_COLLECTION = 'editItemFromCollection',
	DELETE_ALL_TAGS_FROM_COLLECTION = 'deleteAllTagsFromCollection',
	MOVE_ITEM_TO_COLLECTION = 'moveItemToCollection'
}

export enum FORM_ACTIONS {
	LOGIN = `${PATHS.ROOT}?/${SERVER_FORM_ACTIONS.LOGIN}`,
	REGISTER = `${PATHS.ROOT}?/${SERVER_FORM_ACTIONS.REGISTER}`,
	SIGN_OUT = `${PATHS.PROFILE}?/${SERVER_FORM_ACTIONS.SIGN_OUT}`,
	UPDATE_USER = `${PATHS.PROFILE}?/${SERVER_FORM_ACTIONS.UPDATE_USER}`,
	DELETE_USER = `${PATHS.PROFILE}?/${SERVER_FORM_ACTIONS.DELETE_USER}`,
	CREATE_COLLECTION = `${PATHS.API}/${PATHS.COLLECTIONS}?/${SERVER_FORM_ACTIONS.CREATE_COLLECTION}`,
	DELETE_COLLECTION = `${PATHS.COLLECTIONS}?/${SERVER_FORM_ACTIONS.DELETE_COLLECTION}`,
	ONBOARDING_COMPLETED = `${PATHS.PROFILE}?/${SERVER_FORM_ACTIONS.ONBOARDING_COMPLETED}`,
	EDIT_COLLECTION = `${PATHS.COLLECTIONS}?/${SERVER_FORM_ACTIONS.EDIT_COLLECTION}`,
	DELETE_ALL_TAGS_FROM_COLLECTION = `${PATHS.COLLECTIONS}?/${SERVER_FORM_ACTIONS.DELETE_ALL_TAGS_FROM_COLLECTION}`,
	MOVE_COLLECTION = `${PATHS.COLLECTIONS}?/${SERVER_FORM_ACTIONS.MOVE_COLLECTION}`
}
