# This is a basic workflow to automatically build a Svelte app and deploy it to GitHub Pages

name: Pull Request

on: pull_request

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

env:
  DATABASE_URL: ${{ secrets.DATABASE_URL }}
  DATA_PROXY: ${{ secrets.DATA_PROXY }}
  IMAGE_API_TOKEN: ${{ secrets.IMAGE_API_TOKEN }}
  IMAGE_API: ${{ secrets.IMAGE_API }}
  PUBLIC_IMAGE_DELIVERY: ${{ secrets.PUBLIC_IMAGE_DELIVERY }}
  IMAGE_API_ACCOUNT_IDENTIFIER: ${{ secrets.IMAGE_API_ACCOUNT_IDENTIFIER }}
  IS_CI: true
jobs:
  INSTALL:
    name: Install Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/cache@v3
        id: cache-pnpm
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Install
        if: steps.cache-pnpm.outputs.cache-hit != 'true'
        run: |
          pnpm i --frozen-lockfile
          pnpm prisma:gen:ci

  LINT:
    name: Lint
    runs-on: ubuntu-latest
    needs: INSTALL
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Lint
        run: |
          pnpm lint
  VERIFY:
    name: Verify
    runs-on: ubuntu-latest
    needs: INSTALL
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Check
        run: |
          pnpm check
  UNIT_TEST:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: INSTALL
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Unit Test
        run: |
          pnpm test:unit
  PUBLISH_WEBAPP:
    name: Publish to Feature Branch
    environment: PREVIEW
    runs-on: ubuntu-latest
    needs: INSTALL
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Install
        run: |
          pnpm install
      - name: Build
        env:
          IS_CI: false
        run: |
          pnpm build:prod
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cloudkit
          directory: ./apps/web/.svelte-kit/cloudflare
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: ${{ github.head_ref }}
          # Optional: Change the working directory
          # workingDirectory: my-site
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'

          

  PUBLISH_SWAGGER_UI:
    name: Publish to Feature Branch
    environment: PREVIEW
    runs-on: ubuntu-latest
    needs: INSTALL
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 9.1.1
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
      - uses: actions/cache@v3
        with:
          path: ./node_modules
          key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
      - name: Install
        run: |
          pnpm install
      - name: Build
        env:
          IS_CI: false
        run: |
          pnpm build:prod:api
      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: cloudkit-api
          directory: ./apps/swagger-ui/.svelte-kit/cloudflare
          # Optional: Enable this if you want to have GitHub Deployments triggered
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          # Optional: Switch what branch you are publishing to.
          # By default this will be the branch which triggered this workflow
          branch: ${{ github.head_ref }}
          # Optional: Change the working directory
          # workingDirectory: my-site
          # Optional: Change the Wrangler version, allows you to point to a specific version or a tag such as `beta`
          wranglerVersion: '3'
  # Disable until I can figure out a way to deal with the flaky tests
  # E2E_TEST:
  #   name: Run E2E Tests
  #   needs: [INSTALL]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Setup FFmpeg
  #       uses: AnimMouse/setup-ffmpeg@v1
  #     - uses: actions/checkout@v4
  #     - name: Set up Services
  #       run: |
  #         sudo docker-compose up -d
  #     - uses: pnpm/action-setup@v3
  #       with:
  #         version: 9.1.1
  #     - uses: actions/setup-node@v3
  #       with:
  #         node-version: '20'
  #         cache: 'pnpm'
  #     - uses: actions/cache@v3
  #       with:
  #         path: ./node_modules
  #         key: ${{ runner.os }}-${{ hashFiles('./pnpm-lock.yaml', './prisma/dev.schema.prisma', './prisma/prod.schema.prisma') }}
  #     - name: Prisma Generate
  #       run: |
  #         pnpm prisma:gen:dev
  #     - name: Prisma Push
  #       run: |
  #         pnpm prisma:push:dev
  #     - name: Install Playwright Browsers
  #       run: |
  #         pnpm exec playwright install
  #         pnpm playwright install-deps chromium
  #     - name: e2e Test
  #       run: |
  #         pnpm run test:e2e:ci
  #     - uses: actions/upload-artifact@v4
  #       if: ${{ !cancelled() }}
  #       with:
  #         name: playwright-report
  #         path: test-results/
  #         retention-days: 5
        